const iconsList = [
    "A1-Mind",
    "A2-Body-Yoga",
    "A2-Body",
    "A3-We",
    "A4-Context",
    "A5-Ready",
    "accounting",
    "add-lucket-icon",
    "add",
    "airplane",
    "analytics",
    "close",
    "collaboration",
    "dance",
    "diploma",
    "down-arrow",
    "drama",
    "edit",
    "exit2parent",
    "fast-food",
    "focus-icon",
    "forester-house",
    "guitar (1)",
    "guitar",
    "high-five",
    "insurance",
    "karate-master",
    "legal-paper",
    "line",
    "lineThick",
    "minus",
    "money",
    "mortarboard",
    "multiple-users-silhouette",
    "picture",
    "profile-user-with-earth-symbol",
    "reading",
    "remove",
    "scales-of-justice",
    "settings",
    "shovel",
    "success",
    "thought",
    "tourist",
    "up-arrow",
    "warrior",
    "weather-man"
];


export default iconsList;